/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.garpix.gpgtest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int screen=0x7f020001;
    }
    public static final class integer {
        public static final int google_play_services_version=0x7f050000;
    }
    public static final class string {
        public static final int achievement_bored=0x7f040009;
        public static final int achievement_dont_get_cocky_kid=0x7f040007;
        public static final int achievement_humble=0x7f040006;
        public static final int achievement_omg_u_r_teh_uber_leet=0x7f040008;
        public static final int achievement_prime=0x7f040005;
        public static final int achievement_really_really_bored=0x7f04000a;
        public static final int achievement_test=0x7f04000b;
        public static final int app_id=0x7f040004;
        public static final int app_name=0x7f04000e;
        public static final int gamehelper_app_misconfigured=0x7f040001;
        public static final int gamehelper_license_failed=0x7f040002;
        public static final int gamehelper_sign_in_failed=0x7f040000;
        public static final int gamehelper_unknown_error=0x7f040003;
        public static final int leaderboard_easy_high_scores=0x7f04000c;
        public static final int leaderboard_hard_high_scores=0x7f04000d;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
